trigger: none

# NOTE: Service live tests are NOT enabled. This file only enables the analyze stage currently.
extends:
    template: ../../eng/pipelines/templates/stages/archetype-sdk-tests.yml
    parameters:
      ServiceDirectory: batch
      TestTimeoutInMinutes: 240
      BuildTargetingString: azure-batch
      MatrixReplace:
        - TestSamples=.*/true
      EnvVars:
        AZURE_SKIP_LIVE_RECORDING: 'True'
        AZURE_TEST_RUN_LIVE: 'true'